### ISSUE TITLE
Mistake in Appendix A solution

### ISSUE THREAD

**Issue by ghost** [bmuschko/cka-study-guide#1]
Hello!

I think that I found a mistake in appendix A, ch02's solutions.

Shouldn't this
```
$ kubectl create clusterrolebinding api-clusterrolebinding \
  --serviceaccount=apps:api-access --verb=watch,list,get \
  --resource=pods
```
be simply
```
$ kubectl create clusterrolebinding api-clusterrolebinding --clusterrole=api-clusterrole --serviceaccount=apps:api-access
```
since we defined `api-clusterrole` already right before ?

**Comment by bmuschko** [comment]
You are correct. I already fixed that in the source material. It seems like the [page here ](https://learning.oreilly.com/library/view/certified-kubernetes-administrator/9781098107215/app01.html#idm46273267779168) hasn't been updated yet. I will let O'Reilly Media know so they can push a new version.

**Comment by bmuschko** [comment]
Side note: It also seems that the rest of the content in Appendix A hasn't been published or there's an issue with it. It seems to be cut off after the command you mentioned.

**Comment by ghost** [comment]
Thank you for checking! Is there anywhere where I can access the fixed version? It might take some time for them to push it I believe. From what I see, the rest of chapter 2 in appendix A is there at least. I haven't yet gone through other chapters.

Also, perhaps you are already aware but chapter 3 stops after 3  empty sections that are:
```
Creating a Secret
Consuming a Secret as Environment Variables
Mounting a Secret as Volume
```

**Comment by bmuschko** [comment]
Unfortunately, the content is hosted in a private Git repository and can't be accessed without credentials. I will post a message here as soon as I hear back.

Ugh, thanks for letting me know. Chapter 3 hasn't changed drastically but it looks like O'Reilly didn't update that. I let them know. At this time, this gives a poor impression of the content.

**Comment by bmuschko** [comment]
FYI: O'Reilly published the whole book and fixed the issues you mentioned. Thanks again for the note.
