### ISSUE TITLE
Chapter 07 - troubleshooting pod does not work on ARM architecture

### ISSUE THREAD

**Issue by phiroict** [bmuschko/cka-study-guide#2]
This is caused by the mysql server supported is 8.0 and up and the web-app `bmuschko/web-app` in the container does not support the cyphers for authentication: 
The application cannot connect to the the database and returns this error. 
```
Failed to connect to database: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
```

Request to let the example use mysql 8.0+ that is supported by ARM and AMD 

There is a workaround by setting the password directly in the database console by

```
ALTER USER root IDENTIFIED WITH mysql_native_password BY 'password';
```
Or more kubenetes nativly: 
```
k exec -it mysql-db -- mysql -u root -p mysql -e "ALTER USER root IDENTIFIED WITH mysql_native_password BY 'password';"
```
Then you only have fix the actual error :) 

Kind regards.

**Comment by bmuschko** [comment]
Thanks for the pointer. Would you be interested in sending a pull request for the change? At the very least, you'd have to change the container image [here](https://github.com/bmuschko/cka-study-guide/blob/master/app-a/ch07/troubleshooting-service/gemini/mysql-pod.yaml#L10).

**Comment by bmuschko** [comment]
Fixed here:

- https://github.com/bmuschko/cka-study-guide/commit/c6622c1a897128414e6dfce86598a98d66841078
- https://github.com/bmuschko/cka-study-guide/commit/7b20c150a35f9e3975a38b6904f3f93c60ab9fbb
