### ISSUE TITLE
Chapter 2: M1/M2 vagrant fails to build on virtual box beta for ARM

### ISSUE THREAD

**Issue by jamesclair** [bmuschko/cka-study-guide#5]
Received the following error:
```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "6f6af36a-297c-44b2-b6d3-c61fea9a9b90", "--machinereadable"]

Stderr: VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "COMGETTER(ChipsetType)(&aChipset)" at line 53 of file VBoxManageUtils.cpp
VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "COMGETTER(BandwidthControl)(bwCtrl.asOutParam())" at line 2695 of file VBoxManageInfo.cpp
```

It might work if virtual box x86 was ran using Rosetta 2, but I didn't try.  Instead, I'm going to try the following to setup the cluster from scratch and get kubeadm practice using docker-in-docker: https://github.com/brightzheng100/kubernetes-the-hard-way-on-docker

**Comment by jamesclair** [comment]
To elaborate, I'm not suggesting this study guide has an issue.  Instead, the link above or a similar solution is added for folks who want a free way to spin up a cluster with kubeadm locally on M1/M2 macs.

**Comment by bmuschko** [comment]
VirtualBox may not support this kind of environment (yet). Thanks for the pointer. It may be useful for readers with the same setup. I am going to close the issue for now, but we have the reference here.
