### ISSUE TITLE
Chap 2: Can't sign CSR (Minikube, Docker driver, Arm M1)

### ISSUE THREAD

**Issue by jeff-tillinghast** [bmuschko/cka-study-guide#6]
In Chapter 2, following the instructions for Creating a Subject (pp. 15-16). Step 4 ("Sign the CSR...") fails as below:

```
openssl x509 -req -in johndoe.csr -CA /.minikube/ca.crt -CAkey /.minikube/ca.key -CAcreateserial -out johndoe.crt -days 364
Can't open /.minikube/ca.crt for reading, No such file or directory
```

I have confirmed that on my local machine, ~/.minikube contains ca.key and ca.crt:
```
user@LOCAL .minikube % ls
addons			certs			machines
ca.crt			config			profiles
ca.key			files			proxy-client-ca.crt
ca.pem			key.pem			proxy-client-ca.key
cache			logs
cert.pem		machine_client.lock
```
(and both files have content, i.e. certificate and key). Running:

- Minikube v.1.32.2
- Docker Engine 24.0.6
- Apple M1/ARM.

Thanks!

**Comment by bmuschko** [comment]
Based on the error message you provided, it seems like you are missing the `~` character for the path to refer to `.minikube` in the user home directory. The path should be `~/.minikube/ca.crt`. Alternatively, use the full path to the file.

**Comment by jeff-tillinghast** [comment]
Thanks, @bmuschko -- so that's a typo in the book, then, which I can log in the errata. But more importantly, if I put the ~ back in, then it at least finds the signature, but Docker still fails:
```
docker@minikube:~/cert$ openssl x509 -req -in johndoe.csr -CA ~/.minikube/ca.crt -CAkey ~/.minikube/ca.key -CAcreateserial -out johndoe.crt -days 364
Signature ok
subject=CN = johndoe, O = cka-study-guide
Can't open /home/docker/.minikube/ca.crt for reading, No such file or directory
281473422404064:error:02001002:system library:fopen:No such file or directory:../crypto/bio/bss_file.c:69:fopen('/home/docker/.minikube/ca.crt','r')
281473422404064:error:2006D080:BIO routines:BIO_new_file:no such file:../crypto/bio/bss_file.c:76:
unable to load certificate
```

/home/docker is empty.

**Comment by bmuschko** [comment]
Ugh, you are right. There's an issue with the formatting of that command in the book. In the text above the command, you can see another incorrect formatting `<code>...`. Would you mind sending that to the errata?

In regard to the commands, check this script I use during my live training: https://github.com/bmuschko/cka-crash-course/blob/master/exercises/01-rbac/create-user-context.sh

Side note: It seems like you installed minikube with a different user than `docker`. Therefore, it's not visible to the user.

**Comment by jeff-tillinghast** [comment]
Ah-- that makes total sense! And yes, I was going to submit that whole block with the `code` tags as well. Thanks for the script, and I'll take a look at it this afternoon. Much appreciated.

CLOSING: Will submit errata. Error appears to be based on user local machine configuration.

**Comment by bmuschko** [comment]
I added this issue to the errata: https://app.oreilly.com/cs/portal/edit/errata/200061
