### ISSUE TITLE
Chapter02 (Vagrant & Virtualbox, on ARM M1)

### ISSUE THREAD

**Issue by louiseschmidtgen** [bmuschko/cka-study-guide#7]
## Description
I'm attempting to do the fifth exercise of `Chapter02`.
For the problem, I've downloaded the beta version of `Virtualbox` for Apple Silicon. 

It seems like the machine crashes while booting up. 
I thought this might be an issue with Virtualbox on an M1. 
I've attempted to change the code to use `UTM` but I get the same problem.

Are there any tips or tweaks to make this run on my machine?

```
upgrade-version git:(master) ✗ vagrant up
Bringing machine 'k8s-control-plane' up with 'virtualbox' provider...
Bringing machine 'worker-1' up with 'virtualbox' provider...
Bringing machine 'worker-2' up with 'virtualbox' provider...
Bringing machine 'worker-3' up with 'virtualbox' provider...
==> k8s-control-plane: Setting the name of the VM: k8s-control-plane
==> k8s-control-plane: Clearing any previously set forwarded ports...
==> k8s-control-plane: Clearing any previously set network interfaces...
==> k8s-control-plane: Preparing network interfaces based on configuration...
    k8s-control-plane: Adapter 1: nat
    k8s-control-plane: Adapter 2: hostonly
==> k8s-control-plane: Forwarding ports...
    k8s-control-plane: 22 (guest) => 2222 (host) (adapter 1)
==> k8s-control-plane: Running 'pre-boot' VM customizations...
==> k8s-control-plane: Booting VM...
==> k8s-control-plane: Waiting for machine to boot. This may take a few minutes...
    k8s-control-plane: SSH address: 127.0.0.1:2222
    k8s-control-plane: SSH username: vagrant
    k8s-control-plane: SSH auth method: private key
    k8s-control-plane: Warning: Connection reset. Retrying...
The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.

If the provider you're using has a GUI that comes with it,
it is often helpful to open that and watch the machine, since the
GUI often has more helpful error messages than Vagrant can retrieve.
For example, if you're using VirtualBox, run `vagrant up` while the
VirtualBox GUI is open.

The primary issue for this error is that the provider you're using
is not properly configured. This is very rarely a Vagrant issue.
```

**Comment by bmuschko** [comment]
I tried running https://github.com/bmuschko/cka-study-guide/tree/master/app-a/ch02/upgrade-version on my machine which seems to be working fine, however, I do not have a M1. I am not sure if that's the issue though.

I use the following versions:
- Vagrant 2.3.4
- VirtualBox: Version 7.0.6 r155176 (Qt5.15.2)

Can you please give me the version of Vagrant and Virtualbox you are using?

**Comment by louiseschmidtgen** [comment]
Hi @bmuschko,
I am using `Vagrant 2.3.7`.
For Virtualbox I installed the beta version `7.0.11` revision 159210 for M1 from [here](https://www.virtualbox.org/wiki/Testbuilds).

**Comment by bmuschko** [comment]
I tried with the same version of Vagrant and everything still works fine for me.

It seems like Vagrant cannot connect to something, based on this error message:

```
k8s-control-plane: Warning: Connection reset. Retrying...
```

You may want to run with `--debug` to get more detailed information about this. Other than that, I am not sure I can help you with this issue. If you are a O'Reilly learning platform subscriber, you may want to give the [interactive lab](https://learning.oreilly.com/scenarios/cka-prep-upgrading/9781492095514/) a shot.

**Comment by louiseschmidtgen** [comment]
Thanks for your help debugging and for trying to run it using my runtime versions.
When I run the command with the dubug flag I see messages similar to this [issue](https://github.com/hashicorp/vagrant/issues/6957)
```
INFO subprocess: Starting process: ["/usr/local/bin/VBoxManage", "showvminfo", "0de69d99-4073-40db-830b-77caa7ed0966", "--machinereadable"]
DEBUG subprocess: Command not in installer, not touching env vars.
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Exit status: 0
```

```
BoxManageError: There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "0de69d99-4073-40db-830b-77caa7ed0966", "--machinereadable"]

Stderr: VBoxManage: error: The object is not ready
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component SessionMachine, interface IMachine, callee nsISupports
VBoxManage: error: Context: "COMGETTER(BandwidthControl)(bwCtrl.asOutParam())" at line 2695 of file VBoxManageInfo.cpp
>
ERROR warden: Error occurred: The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'aborted' state. Please verify everything is configured
properly and try again.
```
In the VirtualBox logs I can find:
```
LsiLogic#0: Guest issued CDB {0x12, 0x0, 0x0, 0x0, 0x5, 0x0}
LsiLogic#0: 15/0 (Bus/Target) doesn't exist
```

**Comment by bmuschko** [comment]
Thanks for providing more info. Unfortunately, I am not sure why this happens. You may want to log an issue with the [Vagrant project](https://github.com/hashicorp/vagrant/issues). Feel free to link to the Vagrant file in my repo.

**Comment by bmuschko** [comment]
I am sorry that I couldn't help with your issue. I am going to close the issue for now.
