### ISSUE TITLE
Chapter 02 

### ISSUE THREAD

**Issue by louiseschmidtgen** [bmuschko/cka-study-guide#8]
I would suggest updating Exercise 4 in Chapter 02 to reflect the solution for the most recent k8s version.
[Issuing Service Account Token](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#manually-create-an-api-token-for-a-serviceaccount)

Service Account Tokens no longer get generated automatically and should use the [TokenRequest](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-request-v1/) API
```
➜  RBAC git:(main) ✗ kubectl describe serviceaccount api-access -n apps
Name:                api-access
Namespace:           apps
Labels:              <none>
Annotations:         <none>
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

**Comment by bmuschko** [comment]
You are correct. The default behavior has been change in the meantime. The book was written based on Kubernetes 1.23, as indicated on page 1. I assume you are referencing the content on page 18, "Rendering ServiceAccount Details" here?

Unfortunately, I can't easily change a printed book. We'd have to release a second edition. The better place to raise those issues is using the [errata](https://www.oreilly.com/catalog/errata.csp?isbn=0636920548300). The GitHub repository just contains the code snippets used in the book. Would you mind raising an issue there? I will take it into account for the next edition.

**Comment by jeff-tillinghast** [comment]
Recognizing that we can't overhaul the whole book in here, is there a spot where we could discuss alternate solutions to the Service Account Token questions? I've found alternate solutions to generate the new token, and have declarative YAML to assign it to the service account, but haven't been able to do it successfully with imperative CLI commands. Would be happy to be able to join a conversation about alternate approaches for those steps and benefit from everyone's wisdom if there were a better place to do so.

**Comment by bmuschko** [comment]
My [CKS book](https://www.amazon.com/Certified-Kubernetes-Security-Specialist-Depth/dp/1098132971) has been using a newer Kubernetes version that covers the latest changes to ServiceAccounts. Of course, this also has the potential for being changed in Kubernetes.

For general discussions about Kubernetes, I can suggest the [Kubernetes Slack channel](https://kubernetes.slack.com/). There's no book discussion forum at this time, but I'd be happy to discuss things here as part of GitHub issues.

**Comment by louiseschmidtgen** [comment]
Thank you! I've filed a ticket in errata and I hope the feedback helps.

**Comment by bmuschko** [comment]
Thanks, it does.

**Comment by bmuschko** [comment]
Did you already submit the errata at https://www.oreilly.com/catalog/errata.csp?isbn=0636920548300? I do not see it in the system.
