### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE on Troubleshooting excercise chapter

### ISSUE THREAD

**Issue by EsmerlinJM** [bmuschko/cka-study-guide#9]
Hello im attemping the excercise on troublesshooting and i get the error when mysql have the current version `8.1.0` but on `5.6` didnt have this error. It seems to be a missing configuration on mysql-pod.

**Comment by bmuschko** [comment]
Can you please point me to the directory name within the repository that has the issue? Optimally, provide me the URL to it. Thanks!

**Comment by EsmerlinJM** [comment]
> Can you please point me to the directory name within the repository that has the issue? Optimally, provide me the URL to it. Thanks!

https://github.com/bmuschko/cka-study-guide/blob/master/app-a/ch07/troubleshooting-pod/leo/mysql-pod.yaml

This is the error i get: `$ kubectl run --image=byrnedo/alpine-curl tmp --restart=Never --rm -it -- curl 10.109.173.26:3000
If you don't see a command prompt, try pressing enter.
curl: (6) Could not resolve host: curl
Failed to connect to database: ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
pod "tmp" deleted
`

**Comment by bmuschko** [comment]
This exercise is meant to introduce an issue. The introduction to the exercise says the following:

> In this exercise, you will troubleshoot a misconfigured application stack. The application stack consists of a web application implemented using node.js, and a MySQL database. The web application connects to the database upon requesting its endpoint. Web application and MySQL database run in a Pod.

The error message you see is to be expected. The point of this exercise is to troubleshoot and fix the scenario. Have a look at the solution for more information.
